version: '3.8'

services:
  # Go service
  app:
    build: .
    container_name: real_colab_container
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_USER}  
    depends_on:
      - db
    networks:
      - app-network

  # PostgreSQL service
  db:
    image: postgres:13
    container_name: user_service_app
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_USER}
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Named volume for persisting PostgreSQL data
volumes:
  postgres_data:

    # Define custom network for better container communication
networks:
  app-network:
    driver: bridge